README.md, package-lock.json, package.json
Add commitizen to ensure semantic commits
=> chore(tooling): Add commitizen

.snyk, package-lock.json, package.json
Dependency security updates via Snyk. Also adds snyk policy file
=> chore(deps): Security upgrades via Snyk

.bobconfigrc, .npmignore, lib/mdn-bob.js, lib/utils.js, package.json
=> refactor(cleanup): Cleanup and moves index.js to lib/mdn-bob.js

lib/bundler.js, lib/config.js, lib/mdn-bob.js, lib/pageBuilder.js, lib/pageBuilderUtils.js, lib/processor.js, lib/tabbedPageBuilder.js, lib/utils.js
Removes `use strict` adds `#!/usr/bin/env node` to main entry file
=> fix(bin): Remove strict and add node env

.bobconfigrc, lib/mdn-bob.js, lib/utils.js, package-lock.json, package.json
Fix other load paths as some files are bundled with the cli and other provided by the interactive-examples repo.
=> fix(lib): Fix other load paths

lib/pageBuilder.js, lib/pageBuilderUtils.js, live-examples/css-examples/animation/meta.json, live-examples/css-examples/masking/meta.json, live-examples/html-examples/content-sectioning/meta.json, live-examples/js-examples/array/meta.json
Enhance template loading by loading templates based on example type
=> fix(lib): Enhance template loading

bundles.json, lib/bundler.js
Ensure that all editor bundles are loaded from the correct file locations
=> fix(lib): Enhance editor resource loading

.bobconfigrc, bundles.json, lib/bundler.js, lib/mdn-bob.js, lib/pageBuilder.js, lib/pageBuilderUtils.js, lib/processor.js, lib/tabbedPageBuilder.js, lib/utils.js, package-lock.json, package.json
JavaScript bundles for the editor needs to be built by BoB programatically. This adds the required functionality.
=> fix(bob): Build editor JS with browserify

editor/js/editor-libs/tabby.js, editor/js/editor-libs/template-utils.js, editor/js/editor.js, editor/tmpl/live-tabbed-tmpl.html, lib/pageBuilder.js, lib/pageBuilderUtils.js, lib/tabbedPageBuilder.js, live-examples/webapi-examples/document/meta.json, live-examples/webapi-examples/document/queryselector/css/document-queryselector.css, live-examples/webapi-examples/document/queryselector/document-queryselector.html, live-examples/webapi-examples/document/queryselector/js/document-queryselector.js
Implement first version of webapi editor, configurable editor, and querySelector example
=> feat(lib): Implement first version of webapi editor

editor/js/editor-libs/template-utils.js, editor/js/editor.js, live-examples/webapi-examples/document/queryselector/js/document-queryselector.js
Wrap example JS in IIFE to avoid collisions with variables, functions etc. in the larger page scope
=> fix(editor): Wrap example JS in IIFE

live-examples/js-examples/array/array-concat.html
feat(examples):Added example for showing the shorthand syntax of "Array.prototype.concat()".
=> feat(examples):Added example for showing the shorthand syntax of array concat.

renovate.json
Update Renovate config with assignees and labels
=> chore(renovate): Update Renovate config

__tests__/console-utils.test.js, editor/js/editor-libs/console-utils.js
Fixes https://github.com/mdn/interactive-examples/issues/1379
=> Format the JSON object in console

bundles.json, editor/css/libs/codemirror.css, editor/js/lib/codemirror.js
Fixes #382. Updates to latest CodeMirror v5.50.2
To test:
```
npm start
```
Point your browser at http://localhost:4444/pages/js/array-concat.html
=> fix(dependency): update CodeMirror

.travis.yml, package.json
=> Use Node 12

lib/bundler.js, lib/mdn-bob.js, lib/pageBuilder.js, package-lock.json, package.json
Deep down, what happened was that the code mixed sync with async. The `concat` package is all async. Meaning, if you do this:
```javascript
console.log("A")
concat(paths).then(result => console.log("B"))
console.log("C")
```
it will *always* print:
```
A
C
B
```
Now, it's not a huge deal because `concat` is fast but the flaw is that it might not be. You're basically starting a thread but not sticking around to see if it worked. I.e. a fire-and-forget. 
So, if an error happened within that thread, you wouldn't know. Kinda like this imaginary Python code:
```python
print("Sending the ping!")
os.system("curl -XPOST https;//example.com")
print("All done!")
```
If you'd put that into a CLI and run it, it would NOT fail. Despite, the typo on `https;//`. And you would never notice (unless you …
=> refactor: if anything goes wrong, the cli should exit non-zero

bundles.json, lib/bundler.js
To test, run `npm run build` and check. 
But also, from within the `interactive-examples` project root, type:
```
npx install-local ~/dev/MOZILLA/MDN/bob && node node_modules/.bin/mdn-bob
```
fix #404 404
=> mix of relative and absolutish paths

bundles.json, editor/tmpl/live-css-tmpl.html
Remove the version number appended to destFilename for the CSSEditor bundle
fix #410
=> fix(bundle-config): remove version number for csseditor bundle

renovate.json
=> fix(deps): remove renovate config

__tests__/puppeteer-css-editor.test.js, __tests__/puppeteer-js-editor.test.js, __tests__/puppeteer-tabbed-editor.test.js, live-examples/html-examples/content-sectioning/meta.json, live-examples/js-examples/array/array-concat.html
As a first step in [js-examples testing](https://github.com/mdn/interactive-examples/issues/310) I would like to clean up our current unit tests, so I can build on a clean ground.
What do you think @schalkneethling ?
=> test: fix broken unit tests

lib/mdn-bob.js, lib/utils.js
Just a little thing I saw that hurt my eye :)
https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy-sync.md
=> use fs.copySync to copy directories

bundles.json, editor/js/editable-js.js
Add manual call to refresh CodeMirror after 500ms delay
fix #510
=> (fix) add manual refresh to js editor

editor/js/editor.js
- Adds an extra condition to check if the element exist and isn't `null` or `undefined`.
- Resolves #538
=> Check if the element actually exist

editor/js/editor.js
- Specify the query to target the remove the output.
- Makes sure that the output exist and only remove if this is the case.
- Resolves #538 *Seems like I missed this bug*.
=> Safer removal of output

editor/js/editor-libs/events.js
=> Prevents error created by clicking in between example choices

editor/css/editable-css.css, editor/js/editable-css.js
=> Displays clippy button only when hovering .example-choice elements in demo

.github/workflows/auto-merge.yml
Trying this with `GITHUB_TOKEN`
fix #636
=> chore: add github-token entry

.github/workflows/auto-merge.yml
=> use gh token

.eslintrc.json, .github/workflows/codeql-analysis.yml, .github/workflows/main.yml
Update all references to `master` to be `main` for workflows
fix #643
=> fix: publish workflow

lib/pageBuilder.js
Switch to sha256 for file hashing
=> Switch to sha256 for file hashing

__tests__/puppeteer-tabbed-editor.test.js, editor/js/editor-libs/template-utils.js, editor/js/editor.js
Always set the output height to 100% by default
=> fix:editor - fix output height

editor/js/editor-libs/events.js
Ensure that the correct theme is applied on load
=> (fix:theme) ensure correct theme is applied onload

editor/js/editor-libs/events.js
Use `DOMContentLoaded`
fix #722
=> fix:editor use domcontentloaded
