- lib/config.js
- package-lock.json
- package.json
This fixes the failure caused by the latest stable release of cosmiconfig. This also includes a change to lock down the versions of dependencies.
Fix #56
> fix(config): Fix for changes in cosmiconfig

- lib/utils.js
When I build https://github.com/mdn/interactive-example on a Windows machine (`npm run build`), it will return failure on the `copyDirectory` step. Here are the logs.
```
MDN-BOB: Cleaning or creating ./docs/....
MDN-BOB: Copying static assets....
MDN-BOB: Compiling editor JavaScript....
D:\path-to-interactive-examples\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:20
throw errInval
^
Error: D:\path-to-interactive-examples\docs\media\D:\path-to-interactive-examples\node_modules\mdn-bob\editor contains invalid WIN32 path characters.
at mkdirsSync (D:\path-to-interactive-examples\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:18:22)
at mkdirsSync (D:\path-to-interactive-examples\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:36:14)
at Object.copySync …
```
> Fix copyDirectory throwing error when running on Windows

- editor/js/editor-libs/perf.js
This is a temporary hack to allow us to collect perf data for interactive
examples embedded in beta.developer.{mozilla|allizom}.org. We can't know
if we're embedded in a beta domain page or not, so we just post the
same message to both the beta domain and the regular domain.
> Call postMessage() twice when sending perf metrics to the parent.

- editor/js/editor-libs/analytics.js
- editor/js/editor-libs/events.js
- editor/js/editor-libs/mce-utils.js
- editor/js/editor-libs/perf.js
My last PR to this repo modified perf.js to call postMessage()
twice so that data would be sent to the beta domain while we're
supporting that domain. This turns out to be problematic because:
- there were two other postMessage() calls that did not get
the same treatment, so we still weren't getting the data we
needed on the beta domain
- sending extra messages causes angry messages in the developer console
- this hack for the beta domain was temporary because the beta
domain is going away. But we'll have the same problem with the
wiki domain, and that isn't going away any time soon, so we need
a more general solution.
So in this PR, I've found all postMessage() calls and message
event handlers and have removed the origin checks. This means that
interactive examples will be able to …
> Don't specify the origin for postMessage or check origins on message events

- editor/js/editor-libs/console-utils.js
I had no idea how complex interactive-examples and this lib "bob" is. Holy moly!
Anyway, this is an untested attempt to make the JS console support BigInt.
Per the BigInt ECMAScript proposal, if you call the the `toString` operation on `BigInt` types, it will not have the trailing "n". I believe this is not very useful for us, as the browser consoles are displaying it and it is useful to actually see the bigint type in our samples, I believe.
Then this also adds the bigint typed array types, which also should get the same nice formatting as the other typed arrays.
> Add support for BigInts in js console

- lib/pageBuilder.js
- lib/processor.js
This pull request aims to support both `.js` and `.html` source files for the javascript live examples based on #367
> Enable bob to understand standalone JS files for JS examples

- lib/mdn-bob.js
As I've seen in two error handlers we just print `${error}` as a string which was strange to me.
Maybe it is just a typo so I would like to fix them.
If it intentionally behaves like this then please close this pull request.
> Print detailed error messages during build

- editor/tmpl/live-js-tmpl.html
- editor/tmpl/live-tabbed-tmpl.html
Fixes CSS and JS references still referencing old version of CodeMirror
Fixes #394
> fix(dependency): fix incorrect CodeMirror references

- README.md
- package.json
Adds information on using Conventional Changelog conventions via cz-cli
fix #398
> fix(docs): add cz-cli docs

- README.md
Add docs on running Bob locally inside a local checkout of the interactive examples repo
fix #405
> fix(docs): run Bob inside interactive examples locally

- editor/tmpl/live-css-tmpl.html
- editor/tmpl/live-js-tmpl.html
- editor/tmpl/live-tabbed-tmpl.html
- lib/pageBuilder.js
- lib/pageBuilderUtils.js
After this:
```
▶ head -10 docs/pages/js/array-concat.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>JavaScript Demo: Array.concat()</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="../../css/codemirror-5-50-2.css?v=0e360b5" rel="stylesheet" />
<link href="../../css/editor-js.css?v=0e360b5" rel="stylesheet" />
```
> refactor: cache buster on static assets in rendered html

- bundles.json
- editor/js/editor-libs/tabby.js
Seems to unbreak my pages in local dev! It was breaking before but as of this change I can no longer reproduce it. Yay!
> refactor: the CodeMirror config for tabby also uses autoRefresh

- editor/css/libs/prism.css
- editor/js/lib/prism.js
Updates Prismjs to the latest v1.19.0
Fixes #386
> chore(dependency): update Prismjs

- .bobconfigrc
Ensure media assets directory does not nest examples folder two levels deep
fix #516
> (fix) media assets directory structure

- editor/js/editable-js.js
Reduce the number of miliseconds we wait until doing
a manual refresh of CodeMirror for JS examples from
500ms to 200ms
fix #521
> (fix) reduce js editor timeout

- editor/js/editable-js.js
Do not auto focus JS editor
fix #593
> fix: do not auto focus js editor

- editor/js/editor-libs/console-utils.js
Correctly print the value of objects such as those returned by named capture groups
fix #574
> fix: add support for special object types in console

- .github/workflows/opened-issues-triage.yml
- .github/workflows/opened-pull-requests.yml
Adds two new workflows:
1. Newly opened issues are added to the MDN Web Docs project and moved into the Issues Awaiting Triage column
2. Newly opened pull requests are added to the MDN Web Docs project and moved into the Ready for Review column
> fix: add workflows for new issues and pull requests

- .github/workflows/main.yml
Use `GITHUB_TOKEN` for main workflow
fix #638
> fix: use appropriate GitHub token

- .github/workflows/auto-merge.yml
Switch to reusable `auot-merge` from `workflows` repo
fix #658
> chore: use reusable auto-merge

- editor/css/editable-css.css
- editor/js/editable-css.js
This dynamically adds a button to each example choice:
* styled as the arrow that indicated current choice, but in gray. If someone uses a keyboard
* in tab order with 0 opacity (it will visually show once it has focus)
* it can be activated with just a keyboard like any button
* it has an accessible name of “Choose example x”
Example of it in use:
https://user-images.githubusercontent.com/178782/151399525-ec316351-c833-4aa1-976a-eb882f687ba2.mov
This could fix #688
> Add button to each example for keyboard use

- editor/js/editable-wat.js
- live-examples/wat-examples/statements/loop.wat
For that I moved the call to `compileWat` into the `try`.
Here we have a problem, since `WebAssembly.instantiateStreaming` is async, and the way we capture errors is by `try catch`, so unless we await the instantiation call, catch will not get the error.
So I've changed the function that runs the JS to an async function, and that is now awaited before the catch.
But if we actually want the runtime errors to show up in the output, then I'll also have to change each example to use await, something like the following
```JavaScript
var url = "{%wasm-url%}";
await WebAssembly.instantiateStreaming(fetch(url), {console});
```
For now, there is no regression, and there is the benefit of the compilation errors being displayed properly, so I think that this can be merged safely even though we need …
> (fix:bug) Wasm examples, display errors in output

- editor/css/editor-libs/common.css
This sets the CodeMirror cursor to black in light mode and white in dark mode.
fix #718
> fix:editor style cursor for light and dark modes
